stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:18
  script:
    - cd api
    - npm install
    - npm test
    - cd ../view
    - npm install 
    - npm test

build:
  stage: build
  image: docker:latest

  script:
    - docker build -t my-backend ./api
    - docker build -t my-frontend ./view

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose up -d
  when: manual