services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # change-le
      MYSQL_DATABASE: example
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: example
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./view
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:
